# Generated by Django 5.0.2 on 2024-02-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="product",
        ),
        migrations.DeleteModel(
            name="Unit",
        ),
    ]
