# Generated by Django 5.0.2 on 2024-03-01 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_sale_total_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='pur_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
